from sunau import AUDIO_FILE_ENCODING_LINEAR_16
from django.db import models

# Create your models here.
class User_Registration_CA(models.Model):
    User_Id = models.AutoField(primary_key=True)
    Name = models.CharField(max_length=20, null=True, blank=True)
    Father_name = models.CharField(max_length=100, null=True, blank=True)
    Aadhar = models.CharField(max_length=100, null=True, blank=True)
    Pan = models.CharField(max_length=100, null=True, blank=True)
    Enery_bill = models.CharField(max_length=100, null=True, blank=True)
    Gst = models.CharField(max_length=20, null=True, blank=True)
    Email_Id = models.EmailField(max_length=50, null=True, blank=True)
    Mobile = models.CharField(max_length=50, null=True, blank=True)
    Bank_name = models.CharField(max_length=100, null=True, blank=True)
    Account_Holder_Name = models.CharField(max_length=100, null=True, blank=True)
    Account_Number = models.CharField(max_length=25, null=True, blank=True)
    IFSC = models.CharField(max_length=15, null=True, blank=True)
    Otp = models.CharField(max_length=20, null=True, blank=True)
    Payment_Status = models.IntegerField(blank=True, null=True, default=0)
    Pan_Card_Image = models.FileField(upload_to='media', null=True, blank=True)
    Gst_Image = models.FileField(upload_to='media', null=True, blank=True)
    Enery_bill_image = models.FileField(upload_to='media', null=True, blank=True)
    Add1 = models.CharField(max_length=100, null=True, blank=True)
    Add2 = models.CharField(max_length=100, null=True, blank=True)
    State = models.CharField(max_length=30, null=True, blank=True)
    Pincode = models.CharField(max_length=6, null=True, blank=True)
    City = models.CharField(max_length=50, null=True, blank=True)
    District = models.CharField(max_length=50, null=True, blank=True)
    Old_id= models.CharField(max_length=50, null=True, blank=True)
    New_id= models.CharField(max_length=50, null=True, blank=True)
    Is_Approved = models.IntegerField(blank=True, null=True, default=0)
    Created_By = models.CharField(max_length=20, null=True, blank=True)
    Updated_By = models.CharField(max_length=20, null=True, blank=True)
    Updated_Date = models.DateField(null=True, blank=True)
    Status = models.IntegerField(blank=True, null=True, default=0)
    Is_Deleted = models.IntegerField(blank=True, null=True, default=0)
    From_Date = models.IntegerField(blank=True, null=True, default=0)
    Till_Date = models.IntegerField(blank=True, null=True, default=0)

    Tariff_Code = models.CharField(max_length=50, null=True, blank=True)
    Upload_Aaadhar_Id = models.FileField(upload_to='media', null=True, blank=True)
    Upload_Pan_Id = models.FileField(blank=True, null=True, default=0)
    Domicile_No = models.CharField(max_length=50, null=True, blank=True)
    Upload_Domicile_Id = models.FileField(upload_to='media', null=True, blank=True)
    Consumer_Payment_Mode = models.CharField(max_length=50, null=True, blank=True)
    Bank_Id = models.CharField(max_length=50, null=True, blank=True)
    Re_Enter_Account_No = models.CharField(max_length=50, null=True, blank=True)
    Contractor_Id = models.CharField(max_length=50, null=True, blank=True)
    Reference_No = models.CharField(max_length=50, null=True, blank=True)
    Ivrs_No = models.CharField(max_length=50, null=True, blank=True)
    Sign_Status = models.CharField(max_length=50, null=True, blank=True)
    Add_Date = models.DateField(null=True, blank=True)

    Dc_Code = models.CharField(max_length=50, null=True, blank=True)
    Collection_Agent_Name = models.CharField(max_length=50, null=True, blank=True)
    Applicant_Name_Aadhar = models.CharField(max_length=50, null=True, blank=True)
    Applicant_Name_Ivrs = models.CharField(max_length=50, null=True, blank=True)
    Dob = models.DateField(null=True, blank=True)
    Gender = models.CharField(max_length=50, null=True, blank=True)
    Photo_File = models.FileField(upload_to='media', null=True, blank=True)
    Address_Ivrs =  models.CharField(max_length=50, null=True, blank=True)
    Refund_Status = models.CharField(max_length=50, null=True, blank=True)
    Refund_Remarks = models.CharField(max_length=50, null=True, blank=True)
    Gst_Confirm = models.CharField(max_length=50, null=True, blank=True)
    # Gst_Confirm = models.CharField(max_length=50, null=True, blank=True)
    Is_Enable = models.BooleanField(default = True, null=True, blank=True)
    Security_Deposit = models.IntegerField(blank=True, null=True)
    payment_date = models.DateTimeField(blank=True, null=True)
    
class Pin_Code_Table_Master(models.Model):
    Pincode_number = models.IntegerField(blank=True, null=True, default=0)
    City = models.CharField(max_length=255,null=True)
    District = models.CharField(max_length=255,null=True)
    State = models.CharField(max_length=255,null=True)
    Created_By = models.CharField(max_length=20, null=True, blank=True)
    Created_Date = models.DateTimeField(blank=True,null=True)
    Updated_By = models.CharField(max_length=20, null=True, blank=True)
    Updated_Date = models.DateField(null=True, blank=True)
    Status = models.IntegerField(blank=True, null=True, default=0)    
 

class Report_Data(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.CharField(max_length=15, null=True, blank=True)
    name = models.CharField(max_length=20, null=True, blank=True)
    amount = models.EmailField(max_length=50, null=True, blank=True)
    def __str__(self):
        return self.name
import datetime
datetime.datetime.now().strftime("%Y-%d-%m %H:%M:%S")

class Collection_Agent(models.Model):
    Name = models.CharField(max_length=255,null=True)
    Customomer_Id = models.CharField(max_length=255,null=True)
    Customer_name = models.CharField(max_length=255,null=True)
    Customer_bill_amount = models.CharField(max_length=255,null=True)
    Customer_payment_date =  models.CharField(max_length=255,null=True)
    Customer_payment_month = models.CharField(max_length=255,null=True)
    Customer_payment_year = models.CharField(max_length=255,null=True)
    Month = models.CharField(max_length=255,null=True)
    Is_commission = models.CharField(max_length=255,null=True)
    commission_amount = models.CharField(max_length=255,null=True)
    Gst_ammount = models.CharField(max_length=255,null=True)
    Collection_agent_id = models.CharField(max_length=255,null=True)
    Collection_agent_Name = models.CharField(max_length=255,null=True)
    Contractor_id = models.CharField(max_length=255,null=True)
    Is_process = models.CharField(max_length=255,null=True)
    Is_Gst= models.CharField(max_length=255,null=True)
    invoce = models.IntegerField(blank=True, null=True, default=0)
    invoce_no = models.IntegerField(blank=True, null=True, default=0)
    Invoice_Number = models.CharField(max_length=50,null=True,blank=True)




class Payudata_main1(models.Model):
	user =  models.CharField(max_length=100,null=True,blank=True)
	Payment_For = models.CharField(max_length=100, null=True, blank=True)
	Hash_Id = models.CharField(max_length=255, null=True, blank=True)
	date = models.DateField(null=True, blank=True)
	Payu_Status = models.CharField(max_length=50, null=True, blank=True)
	Txdid = models.CharField(max_length=50, null=True, blank=True)
	Productinfo = models.CharField(max_length=100, null=True, blank=True)
	Firstname = models.CharField(max_length=100, null=True, blank=True)
	Lastname = models.CharField(max_length=100, null=True, blank=True)
	Contact_No = models.CharField(max_length=15, null=True, blank=True)
	Email_Id = models.EmailField(max_length=50, null=True, blank=True)
	Paymentgateway_Type = models.CharField(max_length=50, null=True, blank=True)
	Encrypted_PaymentId = models.CharField(max_length=100, null=True, blank=True)
	Bank_Ref_Num = models.CharField(max_length=150, null=True, blank=True)
	Bankcode = models.CharField(max_length=50, null=True, blank=True)
	Name_On_Card = models.CharField(max_length=50, null=True, blank=True)
	Cardnum = models.CharField(max_length=50, null=True, blank=True)
	Payu_Moneyid = models.CharField(max_length=50, null=True, blank=True)
	Netamount_Debited = models.CharField(max_length=50, null=True, blank=True)
   

class invoice_data(models.Model):
    invoice_user_reg = models.ForeignKey(User_Registration_CA,on_delete=models.CASCADE,null=True,blank=True)
    invoice_coll_agent = models.ForeignKey(Collection_Agent,on_delete=models.CASCADE,null=True,blank=True)
    name = models.CharField(max_length=20, null=True, blank=True)
    aadhar = models.CharField(max_length=100, null=True, blank=True)
    pan = models.CharField(max_length=100, null=True, blank=True)
    enery_bill = models.CharField(max_length=100, null=True, blank=True)
    Gst = models.CharField(max_length=20, null=True, blank=True)
    email_Id = models.EmailField(max_length=50, null=True, blank=True)
    mobile = models.CharField(max_length=50, null=True, blank=True)
    bank_name = models.CharField(max_length=100, null=True, blank=True)
    account_Holder_Name = models.CharField(max_length=100, null=True, blank=True)
    account_Number = models.CharField(max_length=25, null=True, blank=True)
    ifsc = models.CharField(max_length=15, null=True, blank=True)
    payment_Status = models.IntegerField(blank=True, null=True, default=0)
    Address = models.CharField(max_length=100, null=True, blank=True)
    State = models.CharField(max_length=30, null=True, blank=True)
    Pincode = models.CharField(max_length=6, null=True, blank=True)
    City = models.CharField(max_length=50, null=True, blank=True)
    District = models.CharField(max_length=50, null=True, blank=True)
    updated_Date = models.DateField(null=True, blank=True)
    authorised_signatory = models.CharField(max_length=50, null=True, blank=True)
    note = models.CharField(max_length=50, null=True, blank=True)
    contractor_id = models.CharField(max_length=255,null=True)
    commission_amount = models.CharField(max_length=255,null=True)
    bill_amount = models.CharField(max_length=255,null=True)
    bank_ref_num = models.CharField(max_length=255,null=True)
    add = models.CharField(max_length=255,null=True)
    Customomer_Id = models.CharField(max_length=255,null=True)
    flag = models.IntegerField(blank=True, null=True, default=0)


class invoice(models.Model):
    id = models.AutoField(primary_key=True)
    invoice_user_reg = models.ForeignKey(User_Registration_CA,on_delete=models.CASCADE,null=True,blank=True)
    invoice_coll_agent = models.ForeignKey(Collection_Agent,on_delete=models.CASCADE,null=True,blank=True)

    commission_amount = models.FloatField(blank=True, null=True, default=0)
    bill_amount = models.FloatField(blank=True, null=True, default=0)
    gst_amount = models.FloatField(blank=True, null=True, default=0)
    date  = models.DateTimeField(auto_now=True,null=True)
    
    commercial = models.IntegerField(blank=True, null=True, default=0)
    finance = models.IntegerField(blank=True, null=True, default=0)
    otp = models.CharField(max_length=255,null=True)

class Generated_Invoice(models.Model):
    Agent_log = models.ForeignKey(User_Registration_CA,on_delete=models.CASCADE,null=True,blank=True)
    Invoice_Number = models.CharField(max_length=50,null=True,blank=True,unique=True)
    Commission_Amount = models.FloatField(blank=True,null=True,default=0)
    Cgst  = models.FloatField(blank=True,null=True,default=0)
    Sgst = models.FloatField(blank=True,null=True,default=0)
    Created_Date = models.DateTimeField(blank=True,null=True)
    Service_Date = models.CharField(max_length=50,blank=True,null=True)
    Commercial_Flag = models.IntegerField(blank=True,null=True,default=0)
    Finance_Flag = models.IntegerField(blank=True,null=True,default=0)
    Contractor_Id = models.CharField(max_length=20,null=True,blank=True)
    Name = models.CharField(max_length=20, null=True, blank=True)
    Father_name = models.CharField(max_length=100, null=True, blank=True)
    Aadhar = models.CharField(max_length=100, null=True, blank=True)
    Pan = models.CharField(max_length=100, null=True, blank=True)
    Enery_bill = models.CharField(max_length=100, null=True, blank=True)
    Gst = models.CharField(max_length=20, null=True, blank=True)
    Email_Id = models.EmailField(max_length=50, null=True, blank=True)
    Mobile = models.CharField(max_length=50, null=True, blank=True)
    Bank_name = models.CharField(max_length=100, null=True, blank=True)
    Account_Holder_Name = models.CharField(max_length=100, null=True, blank=True)
    Account_Number = models.CharField(max_length=25, null=True, blank=True)
    IFSC = models.CharField(max_length=15, null=True, blank=True)
    Add1 = models.CharField(max_length=100, null=True, blank=True)
    Add2 = models.CharField(max_length=100, null=True, blank=True)
    State = models.CharField(max_length=30, null=True, blank=True)
    Pincode = models.CharField(max_length=6, null=True, blank=True)
    City = models.CharField(max_length=50, null=True, blank=True)
    District = models.CharField(max_length=50, null=True, blank=True)
    Payable_Amount = models.FloatField(blank=True,null=True,default=0)
    Reference_No = models.CharField( max_length=255,blank=True,null=True)
    Total_Invoices = models.CharField(max_length=50,blank=True,null=True)
 
class Commerical_invoice(models.Model):
    Total_Invoices = models.IntegerField(blank=True,null=True,default=0)
    Contractor_Id = models.CharField(max_length=50,blank=True,null=True)
    Total_Commision = models.FloatField(blank=True,null=True,default=0)
    Total_GST = models.FloatField(blank=True,null=True,default=0)
    Total_Payable_Amount = models.FloatField(blank=True,null=True,default=0)
    Invoice_number = models.CharField(max_length=255,blank=True,null=True)
    Reference_No = models.CharField( max_length=255,blank=True,null=True)
    Created_Date = models.DateField(null=True, blank=True)


class CA_Deregistration(models.Model):
    id = models.AutoField(primary_key=True)
    agent_id= models.ForeignKey(
        'User_Registration_CA', models.DO_NOTHING, db_column='User_Id', related_name='agent_id')
    Contractor_Id = models.CharField(max_length=50,blank=True,null=True)
    Invoice_Number = models.CharField(max_length=50,null=True,blank=True,unique=True)
    Deposit_amount = models.FloatField(blank=True,null=True,default=0)
    Reference_No = models.CharField( max_length=255,blank=True,null=True)
    Email_Id = models.EmailField(max_length=50, null=True, blank=True)
    Mobile = models.CharField(max_length=50, null=True, blank=True)
    Bank_name = models.CharField(max_length=100, null=True, blank=True)
    Account_Holder_Name = models.CharField(max_length=100, null=True, blank=True)
    Account_Number = models.CharField(max_length=25, null=True, blank=True)
    IFSC = models.CharField(max_length=15, null=True, blank=True)
    Commercial_Flag = models.BooleanField(default=True) 
    Finance_Flag = models.BooleanField(default=False)
    Name = models.CharField(max_length=20, null=True, blank=True)
    Father_name = models.CharField(max_length=100, null=True, blank=True)
    Aadhar = models.CharField(max_length=100, null=True, blank=True)
    Pan = models.CharField(max_length=100, null=True, blank=True)
    Add1 = models.CharField(max_length=100, null=True, blank=True)
    Add2 = models.CharField(max_length=100, null=True, blank=True)
    State = models.CharField(max_length=30, null=True, blank=True)
    Pincode = models.CharField(max_length=6, null=True, blank=True)
    City = models.CharField(max_length=50, null=True, blank=True)
    District = models.CharField(max_length=50, null=True, blank=True)
    gst_no = models.CharField(max_length=50, null=True, blank=True)
    is_refund = models.BooleanField(default=False)
    voucher_code = models.CharField(max_length=50, null=True, blank=True)
    is_security_refund = models.BooleanField(default=False)
    is_deregister = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True, blank=True)
    updated_date = models.DateTimeField(auto_now_add=True, blank=True)

class CA_Bank_Update_Req(models.Model):
    id = models.AutoField(primary_key=True)
    agent_id= models.ForeignKey(
        'User_Registration_CA', models.DO_NOTHING, db_column='User_Id')
    contractor_id = models.IntegerField(null=True, blank=True)
    agent_name = models.CharField(max_length=100, null=True, blank=True)
    bank_name = models.CharField(max_length=100, null=True, blank=True)
    account_Holder_Name = models.CharField(max_length=100, null=True, blank=True)
    account_Number = models.CharField(max_length=25, null=True, blank=True)
    ifsc = models.CharField(max_length=15, null=True, blank=True)
    passbook_image = models.ImageField(upload_to='CA_bank_passbook',null=True, blank=True)  
    is_new_details = models.BooleanField(null=True, blank=True)
    created_date = models.DateTimeField(auto_now_add=True, blank=True)
    approved_by = models.CharField(max_length=25, null=True, blank=True)
    approved_person_id =models.CharField(max_length=25, null=True, blank=True)
    is_approved = models.BooleanField(default=False)
    is_rejected = models.BooleanField(default=False)
    reject_remark = models.CharField(max_length=250, null=True, blank=True)
    
    
